/**
 * Application of the Drizzle migrations.
 * The SQL migrations are generated by `npm run db:generate` in src/db/migrations.
 *
 * This module stays independent of Electron (also used by the tests). The main
 * process resolves the migrations folder itself depending on the context
 * (dev/packaged) and passes it to runMigrations.
 */

import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import type { DB } from "./client.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Migrations folder relative to the source code (src/db/migrations).
 * Correct when running from the sources (tests, tsx). For the Electron bundle,
 * the main provides an explicit path to runMigrations.
 */
export function sourceMigrationsFolder(): string {
  return resolve(__dirname, "migrations");
}

/** Applies all pending migrations to the database, from the given folder. */
export function runMigrations(db: DB, migrationsFolder: string = sourceMigrationsFolder()): void {
  migrate(db, { migrationsFolder });
}
